version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_manager_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - tg_manager_net

  nginx:
    image: nginx:alpine
    container_name: tg_manager_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - tg_manager_net

  mysql:
    image: mysql:8.0
    container_name: tg_manager_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-tg_manager}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-sail}
    volumes:
      - tg_manager_db:/var/lib/mysql
    networks:
      - tg_manager_net

  redis:
    image: redis:alpine
    container_name: tg_manager_redis
    restart: unless-stopped
    volumes:
      - tg_manager_redis_data:/data
    networks:
      - tg_manager_net

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_manager_horizon
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan horizon
    depends_on:
      - app
      - redis
      - mysql
    networks:
      - tg_manager_net

networks:
  tg_manager_net:
    driver: bridge

volumes:
  tg_manager_db:
    driver: local
  tg_manager_redis_data:
    driver: local
